Guía 9: Introducción a arreglos de numpy

Ingeniería en Estadística, Universidad de Valparaíso

Profesor: Eduardo Jorquera - eduardo.jorquera@postgrado.uv.cl

La librería de numpy es ampliamente usada y es fundamental para la computación científica. Contiene, entre otras cosas:

* Objetos N-dimensionales de alta capacidad
* Funciones de difusión sofisticadas
* Herramientas para integrar otros lenguages de programación como C/C++ y Fortran.
* Tiene la capacidad de operar con álgebra lineal, transformaciones matemáticas y números aleatorios.

La característica central de Numpy es el objeto arreglo. Un arreglo puede ser creado a partir de una lista:

In [2]:
import numpy as np
a = np.array([1, 4, 5, 8], float)
print(a)
type(a)

[1. 4. 5. 8.]


numpy.ndarray

Aquí la función toma dos argumentos: la lista que será convertida en arreglo y el tipo de objeto que está en cada elemento de la lista. La ventaja de los arreglos de Numpy, es que los objetos pueden ser manipulados de manera similar que a una lista:

In [13]:
print(a[:1])
print(a[3])
a[0]=5
print(a)

[5.]
8.0
[5. 4. 5. 8.]


Los arreglos pueden ser mutidimensionales. No así como las listas, se puede acceder a una posición del arreglo con comas dentro de los brackets:

In [14]:
a = np.array([[1, 2, 3], [4, 5, 6]], float)
print(a)
print(a[0,0])
print(a[0,1])

[[1. 2. 3.]
 [4. 5. 6.]]
1.0
2.0


También se puede trabajar con arreglos dividiéndolos en varias partes:

In [21]:
a = np.array([[1, 2, 3], [4, 5, 6]], float)
print(a[1,:])
print(a[:,2])
print(a[-1:,-2:])

[4. 5. 6.]
[3. 6.]
[[5. 6.]]


Pregunta: Cómo mostrar todos los elementos de la matriz menos la primera columna?

A través del mismo objeto del arreglo se puede retornar una tupla con el tamaño del arreglo en cada dimensión:

In [22]:
a.shape

(2, 3)

La propiedad **.dtype** muestra el tipo de valores almacenados en el arreglos:

In [24]:
a.dtype

dtype('float64')

Cuando se trabaja con un arreglo, **len** retorna la primera dimensión:

In [26]:
a = np.array([[1, 2, 3], [4, 5, 6]], float)
len(a)

2

**in** puede ser usado para saber si un valor está o no en un arreglo:

In [29]:
a = np.array([[1, 2, 3], [4, 5, 6]], float)
print(2 in a)
print(0 in a)

True
False


Un arreglo puede ser redimensionado (siempre que su forma original lo permita):

In [32]:
a = np.array(range(10), float)
print(a)
a = a.reshape((5, 2))
print(a)
print(a.shape)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[[0. 1.]
 [2. 3.]
 [4. 5.]
 [6. 7.]
 [8. 9.]]
(5, 2)
