Guía 10: Arreglos de numpy

Ingeniería en Estadística, Universidad de Valparaíso

Profesor: Eduardo Jorquera - eduardo.jorquera@postgrado.uv.cl

Los arreglos de numpy también pueden ser pasados a lista:

In [3]:
import numpy as np

a = np.array([1, 2, 3], float)
print(a)
print(a.tolist())
print(list(a))

[1. 2. 3.]
[1.0, 2.0, 3.0]
[1.0, 2.0, 3.0]


Un arreglo de numpy puede transformarse en una cadena de caracteres binaria y recuperarla usando una función inversa:

In [7]:
a = np.array([1, 2, 3], float)
s = a.tostring()
print(s)
np.fromstring(s)

b'\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\x00@\x00\x00\x00\x00\x00\x00\x08@'


/usr/lib64/python3.6/site-packages/ipykernel_launcher.py:4: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  after removing the cwd from sys.path.


array([1., 2., 3.])

Es posible rellenar un arreglo con un solo valor:

In [13]:
a = np.array([1, 2, 3], float)
print(a)
a.fill(0)
print(a)

[1. 2. 3.]
[0. 0. 0.]


Se puede transponer una matriz fácilmente con `.transponse`

In [17]:
a = np.array([[1, 2, 3], [4, 5, 6]], float)
print(a)
a.transpose()

[[1. 2. 3.]
 [4. 5. 6.]]


array([[1., 4.],
       [2., 5.],
       [3., 6.]])

También se puede transformar a un vector "plano" con

In [18]:
a.flatten()

array([1., 2., 3., 4., 5., 6.])

Veamos la concatenación más a fondo:

In [19]:
a = np.array([[1, 2], [3, 4]], float)
b = np.array([[5, 6], [7,8]], float)
print(np.concatenate((a,b)))
print(np.concatenate((a,b), axis=0))
print(np.concatenate((a,b), axis=1))

[[1. 2.]
 [3. 4.]
 [5. 6.]
 [7. 8.]]
[[1. 2.]
 [3. 4.]
 [5. 6.]
 [7. 8.]]
[[1. 2. 5. 6.]
 [3. 4. 7. 8.]]


La dimensionalidad  de un arreglo puede ser incrementada ingresando `newaxis` en la notación de los brackets

In [22]:
a = np.array([1, 2, 3], float)
print(a)
print(a.shape)
print(a[:,np.newaxis])
print(a[:,np.newaxis].shape)

[1. 2. 3.]
(3,)
[[1.]
 [2.]
 [3.]]
(3, 1)
